services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - PYTHONPATH=/app
    depends_on:
      redis:
        condition: service_healthy
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - PYTHONPATH=/app
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A backend.celery_worker:celery_app worker --loglevel=info --pool=threads --concurrency=3

volumes:
  redis_data: